# Uncomment the next line to define a global platform for your project
# platform :ios, '10.3'

target 'ExampleVerifyKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleVerifyKit
pod 'VerifyKit'  

end
